site_name: Surnum√©risme FR
site_url: https://WilfriedStDiall.github.io/surnumerisme-fr/
repo_url: https://github.com/WilfriedStDiall/surnumerisme-fr

theme:
  name: mkdocs
  language: fr
  palette:
    scheme: default
  extra_css:
    - styles/extra.css

nav:
  - Accueil: index.md
  - Introduction: introduction.md
  - Sommaire: sommaire.md
  - Chapitres:
      - Chapitre 1: chapitre1.md
      - Chapitre 2: chapitre2.md
      - Chapitre 3: chapitre3.md
      - Chapitre 4: chapitre4.md
      - Chapitre 5: chapitre5.md
      - Chapitre 6: chapitre6.md
      - Chapitre 7: chapitre7.md
      - Chapitre 8: chapitre8.md
      - Chapitre 9: chapitre9.md
      - Chapitre 10: chapitre10.md
      - Chapitre 11: chapitre11.md
  - Lexique: lexique.md
  - Annexe technique: annexe_technique.md
  - Formule Cs: "Formule Cs.md"

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list

plugins:
  - search
